---
title: ""
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls()) 

library(dplyr)
library(tidyr)
library(ggplot2)
library(posterior)

theme_set(theme_classic() + theme(text = element_text(size = 13)))
```


```{r}
source("plot_hddm_samples.R")
```


```{r}
nChain = 4
nSample = 6000
samples_cv = read.csv("Cavanagh_samples.csv")
samples_cv$chain = rep(1:nChain, each = nSample)
samples_cv$sampleNum = samples_cv$X+1
```

```{r}
adjust_sample = function(data) {
  tmp = data %>% 
  select(!c(X, a, t)) %>% 
  pivot_longer(!c(chain, sampleNum), 
               names_to = "paramName", 
               names_prefix = "v_x",
               values_to = "sampleValue") %>%
  group_by(sampleNum) %>% 
  mutate(minOption = paramName[which.min(sampleValue)],
         minValue = min(sampleValue),
         adjValue = sampleValue - minValue) %>%
  pivot_wider(!c(sampleValue, minValue), 
              names_from = paramName, 
              names_prefix = "v",
              values_from  = adjValue) %>%
  ungroup() 
  return(tmp)
}
```

```{r}
samples_cv_adj = adjust_sample(samples_cv)
unique(samples_cv_adj$minOption)
```


```{r}
# check R hat of adjust value 
chain_summary_cv = summarise_draws(
  samples_cv_adj %>%  
    group_by(chain) %>% 
    mutate(`.iteration` = 1:n()) %>%
    rename(`.draw` = sampleNum, 
           `.chain` = chain) %>% select(!c(minOption)))
any(chain_summary_cv$rhat[!is.na(chain_summary_cv$rhat)] > 1.01)
```

```{r}
tmp = samples_cv_adj %>% 
  select(one_of(c(sprintf("v%d", 1:6), "chain", "sampleNum"))) %>% 
  pivot_longer(!c(chain, sampleNum), # into long format
               names_to = "paramName", 
               values_to = "sampleValue") %>%
  mutate(paramName = factor(paramName, levels = sprintf("v%d", 1:6)))
ggplot(tmp, aes(color = factor(chain))) +
  geom_density(aes(sampleValue), size = 0.5) +
  labs(x = "density", y = "sample value", color = "chain",
      title = "adjust posterior sample value (Cavanagh)") +
  facet_wrap(~factor(paramName), scales = "free")
```

# Plot estimates
```{r}
summarize_posterior = function(data) {
  tmp = data %>% 
    select(one_of(sprintf("v%d", 1:6))) %>% 
    pivot_longer(everything(), 
                 names_to = "tmpName", values_to = "sampleValue") %>%
    mutate(x_obs = as.numeric(substr(tmpName, 2, nchar(tmpName))))
  
  tmp2 = tmp %>% group_by(x_obs) %>% 
    summarise(hdi_low = HDIofMCMC(sampleValue)[1],
              hdi_high = HDIofMCMC(sampleValue)[2],
              sampleMean = mean(sampleValue))
  
  return(tmp2)
}
```

```{r, fig.width = 5, fig.height = 5}
summary_data = data.frame(summarize_posterior(samples_cv_adj)) 


ggplot(summary_data, aes(x = x_obs)) + 
  geom_linerange(aes(ymin=hdi_low,ymax=hdi_high))  +
  geom_point(aes(y = sampleMean), size = 2) + 
  labs(x = "value (objective)", y = "value (estimated from ddm)", 
       title = "Cavanagh") + 
  theme(text = element_text(size = 15))

```

```{r}
summarize_posterior2 = function(data) {
  tmp = data %>% 
    select(a, t) %>% 
    pivot_longer(everything(), 
                 names_to = "paramName", values_to = "sampleValue") %>%
    group_by(paramName) %>% 
    summarise(hdi_low = HDIofMCMC(sampleValue)[1],
              hdi_high = HDIofMCMC(sampleValue)[2],
              sampleMean = mean(sampleValue))
  return(tmp)
}
tmp = summarize_posterior(samples_cv_adj) %>% 
  relocate(x_obs, .after = last_col())
tmp2 = summarize_posterior2(samples_cv)

summary_cv = 
  data.frame(type = "Cavanagh", 
             rbind(data.frame(tmp2, x_obs = NA), 
                   data.frame(paramName = "v", tmp)))
save(summary_cv, file = "summary_cv.RData")
```


